import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HamburgerIcon from "@/components/common/HambugIcon";
import FloatingActionButton from "@/components/common/FloatingActionButton";
import LoadingProgressCircle from "@/components/common/LoadingProgressCircle";
import ProviderWrapper from "@/components/common/ProviderWrapper";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import LinearProgress from "@/components/common/LinearProgress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OnYourBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ProviderWrapper>
            <HamburgerIcon />
            <ToastContainer
              position="top-right"
              autoClose={3000}
              closeOnClick
              pauseOnFocusLoss
              pauseOnHover
              draggable
              role="alert"
              newestOnTop
            />
            {children}
            <LinearProgress colorClassName="bg-[black]" />
            <FloatingActionButton />
            <LoadingProgressCircle />
          </ProviderWrapper>
        </body>
      </html>
    </>
  );
}
