import type { Metadata } from "next";
import "./globals.css";
import ProviderWrapper from "@/components/common/ProviderWrapper";
import "react-toastify/dist/ReactToastify.css";
import ClientLayoutWrapper from "@/components/common/ClientLayoutWrapper";
import localFont from 'next/font/local';

const pretendard = localFont({
  src: "../fonts/pretendard/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

const suit = localFont({
  src: "../fonts/suit/SUIT-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-suit",
});

export const metadata: Metadata = {
  title: "OnYourBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} ${suit.variable} font-pretendard`}>
        <ProviderWrapper>
          <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
        </ProviderWrapper>
      </body>
    </html>
  );
}
