import type { Metadata } from "next";
import "./globals.css";
import ProviderWrapper from "@/components/common/wrapper/ProviderWrapper";
import "react-toastify/dist/ReactToastify.css";
import localFont from "next/font/local";
import ChatBotModal from "@/components/common/chatbot/ChatBotModal";
import Footer from "@/components/common/Footer";

const pretendard = localFont({
  src: "../fonts/pretendard/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

const suit = localFont({
  src: "../fonts/suit/SUIT-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-suit",
});

export const metadata: Metadata = {
  title: "YoPle - 요금제 비교 서비스",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} ${suit.variable} font-pretendard`}>
        <ProviderWrapper>
          {children}
          <div className="w-full sticky bottom-8 flex justify-end pr-8">
            <ChatBotModal />
          </div>
          <Footer />
        </ProviderWrapper>
      </body>
    </html>
  );
}
